[build]
 command = "jekyll build"
 publish = "_site/"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "2.7.1"
  
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    Cache-Control = "max-age=2592000"
    Server = ""