name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    steps:
    - uses: actions/checkout@v1
    - name: Build and Deploy
      uses: jdmevo123/akamai-jekyll-netstorage-action@1.0
      env:
        EDGERC: ${{ secrets.EDGERC }}
      with:
        cpcode: 'xxxx'
